### PR TITLE
Add Crossplane registries page

### LINKED ISSUE #62: Add page for Crossplane registries
Crossplane has an ecosystem of extensions and they can be published to any OCI compliant registry for installation into the control plane via Crossplane's package manager. The [crossplane.io](https://www.crossplane.io/) website should help the community find these registries.

The website should have a new page added that lists all public registries for Crossplane packages at `/registries`. This page will start by listing [marketplace.upbound.io](https://marketplace.upbound.io/) and will welcome PRs to add new entries that fit the following criteria:

* Understands the [`xpkg` format](https://github.com/crossplane/crossplane/blob/main/contributing/specifications/xpkg.md) of Crossplane extensions
* Are publicly accessible with publicly viewable repositories
* Offers Crossplane extensions (packages) that can be downloaded and installed by the community

Other related changes:

* The home page header navigation has a "Marketplace" link that goes directly to marketplace.upbound.io. This link should be renamed `Registries` and the link should be updated to point to this new `/registries` listing page.
* The bottom of the home page has a "All things Crossplane. All in one place." section that also points to marketplace.upbound.io. This section should be updated to point to the `/registries` listing page as well.

### PR DESCRIPTION
**Pull request by jeanduplessis**
Fixes #62 

Credit to @pluc for the date fix in the footer as per #58.

### CODE REVIEW

**Review by jbw976 — CHANGES_REQUESTED** [review]
Wow @jeanduplessis, super amazing work here to just bust this out while I was asleep! 😴 😂  - your frontend skills must not be too rusty 🙇‍♂️ 

I want to sync with the steering committee on the exact criteria for adding new entries to the page, so I'm marking this as "request changes" just temporarily to ensure it isn't merged early.

**Comment by jbw976** [comment]
@jeanduplessis, while you're in here, would you mind also updating the "community" page too? 

* This page is poorly named - it's really about vendors that offer Crossplane commercial offerings and/or vendor support. That should be more clear.
* Homepage header link that says `Community`: let's rename that to `Commercial` and point to `/commercial`.
  * other options are `enterprise` or `vendors` if we prefer one of those
* On this commercial page, there's text about "Check out the Upbound Marketplace..." - let's update that copy and link to point to your new Registries page
* Can we create a redirect for `/community` that will redirect folks to `/commercial`?

**Comment by jeanduplessis** [comment]
@jbw976 no problem, I made the changes as requested.

**Review by bassam — APPROVED** [review]

**Review by bobh66 — APPROVED** [review]

**Review by negz — APPROVED** [review]

**Comment by jbw976** [comment]
@crossplane/steering-committee has reviewed these changes in accordance with the CNCF website guidelines and approved this PR. Let's take it live now! 🤩

**Pull request merged**
